FROM microsoft/dotnet:2.1-runtime AS base
RUN apt-get update && \
    apt-get install -y unzip curl && \
    curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg
ARG EXE_DIR=.
COPY ${EXE_DIR}/bin/Debug/netcoreapp2.1/publish/* /cst-csharp-aggregator/
ENTRYPOINT ["dotnet", "/cst-csharp-aggregator/ABB.Ability.IotEdge.CST.Modules.CSharp.InterModuleCommunication.Aggregator.dll"]